version: '3.8'

services:
  gym:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    environment:
      - SERVER_URL=http://server:8010
      - HOST=localhost
      - PORT=0.0.0.0
    networks:
      app_network:
        ipv4_address: 172.16.12.4


networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.12.0/24
          gateway: 172.16.12.1