# Default values for lwmecps-gym

replicaCount: 1

image:
  repository: adeptvin4/lwmecps-gym
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "lwmecps-gym"
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8010

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleUpCooldownPeriod: 180
  scaleDownCooldownPeriod: 180

nodeSelector: {}

tolerations: []

affinity: {}

# MongoDB configuration
mongodb:
  enabled: true
  service:
    name: "lwmecps-gym-mongodb-service"
    type: ClusterIP
    port: 27017
  image:
    repository: mongo
    tag: "6.0"
  auth:
    enabled: true
    rootPassword: ""  # Set this in production
    database: "lwmecps"
    username: "lwmecps"
    password: ""  # Set this in production
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"
    accessMode: ReadWriteOnce
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  backup:
    enabled: false
    schedule: "0 0 * * *"  # Daily at midnight
    retention: 7  # Keep backups for 7 days
    storageClass: "standard"
    size: 5Gi

# Weights & Biases configuration
wandb:
  enabled: true
  apiKey: ""  # Set this in production
  projectName: "lwmecps-gym"
  entity: ""  # Set this in production
  mode: "online"  # or "offline"
  tags: []

# Training configuration
training:
  defaultParameters:
    learningRate: 0.1
    discountFactor: 0.95
    explorationRate: 1.0
    explorationDecay: 0.995
  defaultEpisodes: 1000
  modelSavePath: "/app/models"
  wandbLogsPath: "/app/wandb_logs"
  persistence:
    models:
      enabled: true
      size: 5Gi
      storageClass: "standard"
      accessMode: ReadWriteOnce
    logs:
      enabled: true
      size: 2Gi
      storageClass: "standard"
      accessMode: ReadWriteOnce

# Kubernetes cluster configuration
kubernetes:
  server: "https://kubernetes.default.svc"
  namespace: "default"
  deploymentName: "mec-test-app"
  deployments:
    - "mec-test-app"
  maxPods: 10000 