{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lwmecps-gym.serviceAccountName" . }}
  labels:
    {{- include "lwmecps-gym.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lwmecps-gym.fullname" . }}
  labels:
    {{- include "lwmecps-gym.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lwmecps-gym.fullname" . }}
  labels:
    {{- include "lwmecps-gym.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lwmecps-gym.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lwmecps-gym.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }} 